import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex flex-col justify-center items-center">
        <div className="text-3xl">Which is cuter?</div>
        <div className="p-4" />
        <div className="min-w-[40%] m-4 p-8 flex justify-center items-center bg-slate-200 rounded-xl shadow-2x">
          <div className="w-1/3 text-center font-bold text-3xl text-black">
            VS
          </div>
          <div className="w-1/3 text-center font-bold text-3xl text-black">
            VS
          </div>
          <div className="w-1/3 text-center font-bold text-3xl text-black">
            VS
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
